"""create user table

Revision ID: 1f73c4557e78
Revises: fd10c9f9bd49
Create Date: 2025-05-27 20:17:04.942299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f73c4557e78'
down_revision: Union[str, None] = 'fd10c9f9bd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(timezone=True), # Recomendo adicionar timezone=True
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(timezone=True), # Recomendo adicionar timezone=True
               nullable=False)
    # ### end Alembic commands ###
